NUM_ROUNDS = 3
MATH_OPERATORS = ['+', '-', '*']
MIN_LEN_PROGRESSION = 5
MAX_LEN_PROGRESSION = 10
EVEN_TASK = 'Answer "yes" if the number is even, otherwise answer "no".'
CALC_TASK = 'What is the result of the expression?'
GCD_TASK = 'Find the greatest common divisor of given numbers.'
PROGRESSION_TASK = 'What number is missing in the progression?'
PRIME_TASK = 'Answer "yes" if given number is prime. Otherwise answer "no".'
